### ISSUE TITLE
[meta] Next steps

### ISSUE THREAD

**Issue by LewisGaul** [LewisGaul/declarative-cli#4]
See https://github.com/LewisGaul/declarative-cli/projects/1

- [ ] Rewrite in Rust
- [ ] Write up required/desired capabilities in static CLI declaration
  - 'global' args?
  - read env vars?
  - dynamic hook points?
  - modular structure?
- [ ] Outline comparison of proposed frontends
- [ ] Enhance bot CLI implementation
- [ ] Add tests
